food_delivery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('DBT_BQ_PROJECT', 'project-739a3554-aa69-4eab-9e2') }}"
      dataset: food_delivery_dbt
      threads: 4
      timeout_seconds: 300
      location: asia-southeast1
      retries: 1
